name: Build package

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_pkg:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Checkout Dependecies
      run: |
        git clone https://github.com/bucanero/dbglogger.git       --depth 1
        git clone https://github.com/bucanero/apollo-lib.git      --depth 1
        git clone https://github.com/bucanero/libxmp-lite-ps4.git --depth 1

    - name: Set env vars
      id: slug
      run: |
        echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
        echo "pkg_file=apollo-ps3.pkg" >> $GITHUB_ENV

      # using pre-compiled sdk
    - name: Download PSL1GHT Toolchain
      run: |
        curl -sL https://github.com/bucanero/ps3toolchain/releases/download/ubuntu-latest-fad3b5fb/ps3dev-ubuntu-latest-2020-08-31.tar.gz | tar xvz -C ./
        echo "PS3DEV=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV
        echo "PSL1GHT=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV

    - name: Install dbglogger
      working-directory: dbglogger
      run: |
        make install

    - name: Install apollo-lib
      working-directory: apollo-lib
      run: |
        make install

    - name: Install libxmp-lite
      working-directory: libxmp-lite-ps4
      run: |
        make -f Makefile.ps3 install

    - name: Build Apollo App Package
      run: |
        make createzip
        make pkg

    - name: Push package artifact
      uses: actions/upload-artifact@v3
      with:
        name: apollo-ps3-build_${{ steps.slug.outputs.sha8 }}
        path: ${{ env.pkg_file }}
        if-no-files-found: error
        # don't keep artifacts for too long
        retention-days: 7
